server:
  port: 8081

spring:
  application:
    name: customer

  datasource:
    password: password
    username: myjavablog
    url: jdbc:postgresql://localhost:5432/customer
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    server:
      waitTimeInMsWhenSyncEmpty: 0